resources:
- ../base
- env-ops-configmap.yaml
- rbd8c8a5/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: rbd8c8a5/revision-patch.yaml
  target:
    kind: Service
- path: rbd8c8a5/routing-patch.yaml
  target:
    kind: Service